<?php
declare(strict_types=1);
require dirname(__DIR__) . '/lib/bootstrap.php';
$admin=require_admin();$adminTitle='Enquiries';$adminSection='enquiries';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'read');if(!in_array($status,['new','read','replied','archived'],true))$status='read';db()->prepare('UPDATE enquiries SET status=? WHERE id=?')->execute([$status,$id]);flash('success','Enquiry status updated.');redirect(url('admin/enquiries.php?view='.$id));
}
$viewId=(int)($_GET['view']??0);$viewItem=null;
if($viewId){$stmt=db()->prepare('SELECT e.*,s.title AS service_title FROM enquiries e LEFT JOIN services s ON s.id=e.service_id WHERE e.id=?');$stmt->execute([$viewId]);$viewItem=$stmt->fetch();if($viewItem&&$viewItem['status']==='new'){db()->prepare("UPDATE enquiries SET status='read' WHERE id=?")->execute([$viewId]);$viewItem['status']='read';}}
$statusFilter=(string)($_GET['status']??'');$params=[];$where='';if(in_array($statusFilter,['new','read','replied','archived'],true)){$where='WHERE e.status=?';$params[]=$statusFilter;}
$stmt=db()->prepare("SELECT e.*,s.title AS service_title FROM enquiries e LEFT JOIN services s ON s.id=e.service_id $where ORDER BY e.created_at DESC");$stmt->execute($params);$enquiries=$stmt->fetchAll();
require __DIR__.'/includes/header.php';
?>
<?php if($viewItem):?>
<div class="admin-page-head"><div><a href="<?= e(url('admin/enquiries.php')) ?>">← All enquiries</a><h2>Enquiry #<?= (int)$viewItem['id'] ?></h2><p>Received <?= e(date('l, d F Y \a\t g:i a',strtotime($viewItem['created_at']))) ?></p></div><span class="status status--<?= e($viewItem['status']) ?>"><?= e($viewItem['status']) ?></span></div>
<div class="admin-grid enquiry-view"><section class="admin-panel"><div class="admin-panel__head"><div><span>Customer request</span><h2><?= e($viewItem['name']) ?></h2></div><span class="mail-state">Email: <?= e($viewItem['mail_status']) ?></span></div><dl class="enquiry-details"><div><dt>Phone</dt><dd><a href="tel:<?= e(preg_replace('/\D+/','',$viewItem['phone'])) ?>"><?= e($viewItem['phone']) ?></a></dd></div><div><dt>Email</dt><dd><?= $viewItem['email']?'<a href="mailto:'.e($viewItem['email']).'">'.e($viewItem['email']).'</a>':'Not provided' ?></dd></div><div><dt>Suburb</dt><dd><?= e($viewItem['suburb']?:'Not provided') ?></dd></div><div><dt>Service</dt><dd><?= e($viewItem['service_title']?:'General enquiry') ?></dd></div><div class="full"><dt>Message</dt><dd><?= nl2br(e($viewItem['message']?:'No additional message.')) ?></dd></div><div class="full"><dt>Source</dt><dd><?= e($viewItem['source_url']?:'Website') ?></dd></div></dl></section><aside class="admin-panel enquiry-actions"><h2>Manage enquiry</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$viewItem['id'] ?>"><label>Status<select name="status"><?php foreach(['new','read','replied','archived'] as $status):?><option value="<?= $status ?>" <?= $viewItem['status']===$status?'selected':'' ?>><?= ucfirst($status) ?></option><?php endforeach;?></select></label><button class="admin-button" type="submit">Update status</button></form><hr><a class="admin-button admin-button--secondary" href="mailto:<?= e((string)$viewItem['email']) ?>?subject=Your JG Cleaning Services enquiry">Reply by email</a><a class="admin-button admin-button--secondary" href="tel:<?= e(preg_replace('/\D+/','',$viewItem['phone'])) ?>">Call customer</a></aside></div>
<?php else:?>
<div class="admin-page-head"><div><span>Customer communication</span><h2>Website enquiries</h2><p>Every form submission is saved here, even if email delivery is unavailable.</p></div></div>
<div class="filter-tabs"><a class="<?= $statusFilter===''?'is-active':'' ?>" href="<?= e(url('admin/enquiries.php')) ?>">All</a><?php foreach(['new','read','replied','archived'] as $status):?><a class="<?= $statusFilter===$status?'is-active':'' ?>" href="<?= e(url('admin/enquiries.php?status='.$status)) ?>"><?= ucfirst($status) ?></a><?php endforeach;?></div>
<section class="admin-panel"><?php if(!$enquiries):?><div class="empty-state">No enquiries match this filter.</div><?php else:?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Service</th><th>Message</th><th>Status</th><th>Email</th><th>Received</th><th></th></tr></thead><tbody><?php foreach($enquiries as $item):?><tr><td><strong><?= e($item['name']) ?></strong><small><?= e($item['phone']) ?></small></td><td><?= e($item['service_title']?:'General') ?></td><td><?= e(mb_strimwidth((string)$item['message'],0,65,'…')) ?></td><td><span class="status status--<?= e($item['status']) ?>"><?= e($item['status']) ?></span></td><td><span class="mail-state mail-state--<?= e($item['mail_status']) ?>"><?= e($item['mail_status']) ?></span></td><td><?= e(date('d M Y',strtotime($item['created_at']))) ?><small><?= e(date('g:i a',strtotime($item['created_at']))) ?></small></td><td><a class="table-action" href="<?= e(url('admin/enquiries.php?view='.$item['id'])) ?>">Open →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>

