<?php
declare(strict_types=1);
require dirname(__DIR__) . '/lib/bootstrap.php';
$admin = require_admin();
$adminTitle = 'Dashboard';
$adminSection = 'dashboard';
$stats = ['pages'=>(int)db()->query('SELECT COUNT(*) FROM pages')->fetchColumn(),'services'=>(int)db()->query('SELECT COUNT(*) FROM services WHERE active=1')->fetchColumn(),'new'=>(int)db()->query("SELECT COUNT(*) FROM enquiries WHERE status='new'")->fetchColumn(),'all'=>(int)db()->query('SELECT COUNT(*) FROM enquiries')->fetchColumn()];
$recent = db()->query('SELECT e.*, s.title AS service_title FROM enquiries e LEFT JOIN services s ON s.id=e.service_id ORDER BY e.created_at DESC LIMIT 6')->fetchAll();
require __DIR__ . '/includes/header.php';
?>
<section class="admin-welcome"><div><span>Website overview</span><h2>Hello, <?= e(explode(' ', $admin['name'])[0]) ?>.</h2><p>Manage the JG Cleaning Services website from one secure dashboard.</p></div><a class="admin-button admin-button--light" href="<?= e(url()) ?>" target="_blank">Open website ↗</a></section>
<div class="stat-grid"><a href="<?= e(url('admin/pages.php')) ?>"><span class="stat-icon">▤</span><strong><?= $stats['pages'] ?></strong><p>Editable pages</p></a><a href="<?= e(url('admin/services.php')) ?>"><span class="stat-icon">✦</span><strong><?= $stats['services'] ?></strong><p>Active services</p></a><a href="<?= e(url('admin/enquiries.php?status=new')) ?>"><span class="stat-icon">✉</span><strong><?= $stats['new'] ?></strong><p>New enquiries</p></a><a href="<?= e(url('admin/enquiries.php')) ?>"><span class="stat-icon">◷</span><strong><?= $stats['all'] ?></strong><p>Total enquiries</p></a></div>
<div class="admin-grid admin-grid--dashboard"><section class="admin-panel"><div class="admin-panel__head"><div><span>Latest activity</span><h2>Recent enquiries</h2></div><a href="<?= e(url('admin/enquiries.php')) ?>">View all →</a></div><?php if (!$recent): ?><div class="empty-state">No enquiries have arrived yet.</div><?php else: ?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Received</th></tr></thead><tbody><?php foreach ($recent as $item): ?><tr><td><a href="<?= e(url('admin/enquiries.php?view=' . $item['id'])) ?>"><strong><?= e($item['name']) ?></strong><small><?= e($item['phone']) ?></small></a></td><td><?= e($item['service_title'] ?: 'General') ?></td><td><span class="status status--<?= e($item['status']) ?>"><?= e($item['status']) ?></span></td><td><?= e(date('d M Y, g:i a', strtotime($item['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><aside class="admin-panel quick-actions"><div class="admin-panel__head"><div><span>Shortcuts</span><h2>Quick actions</h2></div></div><a href="<?= e(url('admin/services.php?action=new')) ?>"><i>＋</i><span><strong>Add a service</strong><small>Create content, SEO and images</small></span></a><a href="<?= e(url('admin/pages.php')) ?>"><i>✎</i><span><strong>Edit page SEO</strong><small>Titles, keywords and descriptions</small></span></a><a href="<?= e(url('admin/settings.php')) ?>"><i>⚙</i><span><strong>Update contact details</strong><small>Phones, email, map and social</small></span></a></aside></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
