<?php
declare(strict_types=1);
require dirname(__DIR__) . '/lib/bootstrap.php';
$admin=require_admin(); $adminTitle='Website Settings'; $adminSection='settings'; $error='';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $textFields=['site_name','site_url','tagline','phone_1','phone_2','email_1','email_2','address','opening_hours','footer_text','social_facebook','social_instagram','social_linkedin','social_youtube','whatsapp_number','whatsapp_message','smtp_host','smtp_port','smtp_encryption','smtp_username','smtp_from_email','smtp_from_name','admin_email'];
        foreach($textFields as $key){$value=trim((string)($_POST[$key]??''));if(str_starts_with($key,'social_')&&$value!==''&&!filter_var($value,FILTER_VALIDATE_URL))throw new RuntimeException('Please enter complete https:// links for social media.');update_setting($key,$value);}
        update_setting('map_embed',sanitize_map_embed((string)($_POST['map_embed']??'')));
        update_setting('mail_enabled',isset($_POST['mail_enabled'])?'1':'0');
        if(trim((string)($_POST['smtp_password']??''))!==''){update_setting('smtp_password_enc',encrypt_secret((string)preg_replace('/\s+/','',(string)$_POST['smtp_password'])));}
        update_setting('logo_main',upload_image('logo_main',(string)setting('logo_main')));
        update_setting('logo_footer',upload_image('logo_footer',(string)setting('logo_footer')));
        if(($_POST['action']??'save')==='test_mail'){
            require_once APP_ROOT.'/lib/mailer.php';
            $mailer=make_mailer();$mailer->addAddress((string)setting('admin_email'));$mailer->Subject='JG Cleaning CMS SMTP test';$mailer->Body=mail_template('Your SMTP settings are working','This test email was sent from the JG Cleaning Services administration panel.','<div style="padding:18px;border-radius:12px;background:#e9f9fd;color:#075e72">PHPMailer connected successfully using the saved website settings.</div>');$mailer->AltBody='JG Cleaning CMS SMTP settings are working.';$mailer->send();
            flash('success','Settings saved and a test email was sent to the admin address.');
        }else flash('success','Website, contact, social and mail settings were saved.');
        redirect(url('admin/settings.php'));
    }catch(Throwable $exception){$error=$exception->getMessage();}
}
require __DIR__.'/includes/header.php';
?>
<div class="admin-page-head"><div><span>Global controls</span><h2>Website settings</h2><p>Update logos, contact details, the map, social profiles, WhatsApp and Gmail SMTP.</p></div><a class="admin-button admin-button--secondary" href="<?= e(url()) ?>" target="_blank">Preview website ↗</a></div>
<?php if($error):?><div class="admin-alert admin-alert--error"><?= e($error) ?></div><?php endif;?>
<form class="admin-form" method="post" enctype="multipart/form-data"><?= csrf_field() ?>
<section class="admin-panel" id="branding"><div class="admin-panel__head"><div><span>Brand</span><h2>Website identity and logos</h2></div></div><div class="admin-form-grid"><label>Website name<input type="text" name="site_name" value="<?= e((string)setting('site_name')) ?>" required></label><label>Website URL <small>Leave blank for automatic detection</small><input type="url" name="site_url" value="<?= e((string)setting('site_url')) ?>" placeholder="https://www.jgcleaningservices.com.au"></label><label class="full">Tagline<input type="text" name="tagline" value="<?= e((string)setting('tagline')) ?>"></label><label class="full">Footer description<textarea name="footer_text" rows="3"><?= e((string)setting('footer_text')) ?></textarea></label></div><div class="image-upload-grid image-upload-grid--logos"><label><strong>Main header logo</strong><span>JPG, PNG, WebP or AVIF up to 5 MB.</span><img src="<?= e(asset((string)setting('logo_main'))) ?>" alt="Current main logo"><input type="file" name="logo_main" accept="image/jpeg,image/png,image/webp,image/avif"></label><label class="dark-preview"><strong>Footer white logo</strong><span>JPG, PNG, WebP or AVIF up to 5 MB.</span><img src="<?= e(asset((string)setting('logo_footer'))) ?>" alt="Current footer logo"><input type="file" name="logo_footer" accept="image/jpeg,image/png,image/webp,image/avif"></label></div></section>
<section class="admin-panel" id="contact"><div class="admin-panel__head"><div><span>Business information</span><h2>Contact details</h2></div><small>Both phone and email fields are available throughout the website.</small></div><div class="admin-form-grid"><label>Primary phone<input type="text" name="phone_1" value="<?= e((string)setting('phone_1')) ?>" required></label><label>Second phone<input type="text" name="phone_2" value="<?= e((string)setting('phone_2')) ?>"></label><label>Primary email<input type="email" name="email_1" value="<?= e((string)setting('email_1')) ?>" required></label><label>Second email<input type="email" name="email_2" value="<?= e((string)setting('email_2')) ?>"></label><label class="full">Address<textarea name="address" rows="2"><?= e((string)setting('address')) ?></textarea></label><label class="full">Opening hours<input type="text" name="opening_hours" value="<?= e((string)setting('opening_hours')) ?>"></label><label class="full">Google Maps iframe embed code <small>Only Google Maps iframe URLs are accepted.</small><textarea name="map_embed" rows="5" placeholder="Paste the Google Maps iframe code here"><?= e((string)setting('map_embed')) ?></textarea></label></div></section>
<section class="admin-panel"><div class="admin-panel__head"><div><span>Online profiles</span><h2>Social media and WhatsApp</h2></div></div><div class="admin-form-grid"><label>Facebook URL<input type="url" name="social_facebook" value="<?= e((string)setting('social_facebook')) ?>"></label><label>Instagram URL<input type="url" name="social_instagram" value="<?= e((string)setting('social_instagram')) ?>"></label><label>LinkedIn URL<input type="url" name="social_linkedin" value="<?= e((string)setting('social_linkedin')) ?>"></label><label>YouTube URL<input type="url" name="social_youtube" value="<?= e((string)setting('social_youtube')) ?>"></label><label>WhatsApp number <small>Include country code, digits only</small><input type="text" name="whatsapp_number" value="<?= e((string)setting('whatsapp_number')) ?>"></label><label>Default WhatsApp message<input type="text" name="whatsapp_message" value="<?= e((string)setting('whatsapp_message')) ?>"></label></div></section>
<section class="admin-panel smtp-panel"><div class="admin-panel__head"><div><span>Enquiry delivery</span><h2>Gmail SMTP and recipient settings</h2></div><label class="switch"><input type="checkbox" name="mail_enabled" value="1" <?= setting('mail_enabled')==='1'?'checked':'' ?>><span></span>Email enabled</label></div><div class="admin-form-grid"><label>SMTP host<input type="text" name="smtp_host" value="<?= e((string)setting('smtp_host')) ?>" required></label><label>SMTP port<input type="number" name="smtp_port" value="<?= e((string)setting('smtp_port')) ?>" required></label><label>Encryption<select name="smtp_encryption"><option value="tls" <?= setting('smtp_encryption')==='tls'?'selected':'' ?>>TLS (recommended, port 587)</option><option value="ssl" <?= setting('smtp_encryption')==='ssl'?'selected':'' ?>>SSL (port 465)</option></select></label><label>SMTP username<input type="email" name="smtp_username" value="<?= e((string)setting('smtp_username')) ?>" required></label><label>SMTP app password <small>Leave blank to keep the encrypted saved password</small><input type="password" name="smtp_password" value="" autocomplete="new-password" placeholder="•••• •••• •••• ••••"></label><label>From email<input type="email" name="smtp_from_email" value="<?= e((string)setting('smtp_from_email')) ?>" required></label><label>From name<input type="text" name="smtp_from_name" value="<?= e((string)setting('smtp_from_name')) ?>"></label><label>Admin recipient email<input type="email" name="admin_email" value="<?= e((string)setting('admin_email')) ?>" required></label></div><div class="smtp-note"><strong>Security:</strong> the SMTP password is encrypted before it is stored and is never displayed back in the browser.</div></section>
<div class="admin-form-actions"><a href="<?= e(url('admin/index.php')) ?>">Cancel</a><div><button class="admin-button admin-button--secondary" type="submit" name="action" value="test_mail">Save &amp; send test email</button><button class="admin-button" type="submit" name="action" value="save">Save all settings</button></div></div></form>
<?php require __DIR__.'/includes/footer.php';?>
